name: 'jimatkaki'
version: '1.0.0'
config-version: 2

profile: 'jimatkaki'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory in which to store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  jimatkaki:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: view
